#!/usr/bin/env bash
# this script outputs a string that returns domain records info

w_w_w () {
        RECORD_TYPE=$(dig "$2"."$1" | awk 'BEGIN{OFS=" ";} /^'$2'/{print $4}')
        DESTINATION=$(dig "$2"."$1" | awk 'BEGIN{OFS=" ";} /^'$2'/{print $5}')
        echo "The subdomain $2 is a $RECORD_TYPE record and points to $DESTINATION"
}
domain=$1
subdomain=$2
sub=( www lb-01 web-01 web-02 )
check () {
    if [[ $subdomain == "" ]]
    then
        for x in "${sub[@]}"
        do
            w_w_w "$domain" "$x"
        done
    else
        w_w_w "$domain" "$subdomain"
    fi
    return 0
}
check
