#!/usr/bin/env bash
# Install nginx web server
apt-get update
apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.html
sed -i '/listen 80 default_server;/a add_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
service nginx restart
