#!/usr/bin/env bash
# Bash script that displays the time for 12 hours and 59 minutes
i=0
j=0
while [ $i -le 12 ]
do
if [ $i -eq $i ]
then
echo "Hour: $i"
while [ $j -le 59 ]
echo $j
((j++))
((i++))
done
done
